### ISSUE TITLE
pynq z1 dma problem

### ISSUE THREAD

**Issue by simpsonshrek** [Xilinx/PYNQ_Workshop#2] opened 2018-08-03 02:52 UTC
Hello, i'm following the DMA tutorial in section 4. The whole flow can work with the bitstream inside the file. However, when i want to reproduce the bitstream file by myself, the whole flow fail. I have follow the block diagram of tutorial, is there anything else i have to set. The following image is my block diagram.
![default](https://user-images.githubusercontent.com/42051979/43621649-279c794a-970b-11e8-8573-1f525c4c052a.PNG)
![default](https://user-images.githubusercontent.com/42051979/43621667-40dde394-970b-11e8-84d0-14e816529b34.PNG)
thanks for your help

**Comment by bellakate** [comment] 2018-08-03 13:06
Hello! I have also  the same block diagram and facing issue importing overlay. importing overlay shows me some key error in dictionary.Any help will be appreciated

**Comment by simpsonshrek** [comment] 2018-08-04 01:57
Maybe you can see this video. I follow these step to import overlay.

https://www.youtube.com/watch?v=Dupyek4NUoI&feature=youtu.be&t=8m13s

**Comment by cathalmccabe** [comment] 2018-08-04 06:59
@simpsonshrek you have given no information about how it fails, and no background information about which board you are using, PYNQ image version, Vivaldo tool version etc. 

@bellakate it would help if you actually posted the full error, and also provided same information as above.

**Comment by simpsonshrek** [comment] 2018-08-04 07:17
I'm using PYNQ Z1 ZYNQ XC7Z020-1CLG400C fpga board, the image file is Pynq-Z1 v2.1 image, the Vivaldo  version is 2016.1. As I use the bit stream file, the process of sending data through DMA work like following image.
![default](https://user-images.githubusercontent.com/42051979/43673629-f1b8b688-97f8-11e8-9b7e-c7a189cbb068.PNG)
![default](https://user-images.githubusercontent.com/42051979/43673637-091d7b7e-97f9-11e8-8503-8656230e216d.PNG)
If I use the bitstream file generate by myself, the whole process will become like this
![default](https://user-images.githubusercontent.com/42051979/43673675-50b75bee-97f9-11e8-8b69-2ba127d5bdde.PNG)
![default](https://user-images.githubusercontent.com/42051979/43673679-6d366a8a-97f9-11e8-8e32-8b18e4c77cd2.PNG)

**Comment by cathalmccabe** [comment] 2018-08-13 09:42
This material is based on the PYNQ v2.0 image 
I'll post an update soon for the v2.2/v2.3 image. 

For now, you should check the documentation for the image you are using.

**Comment by cathalmccabe** [comment] 2018-10-19 09:47
@simpsonshrek can you post this to the PYNQ support forum with full notebook? http://www.pynq.io/support.html
I notice in your design you named the DMAs axi_dma_0 and axi_dma_1
In your code you are using the same labels as the original design (dma_send, dma_recv). Perhaps you have aliased your DMAs, but I expect the issue is something more fundamental and that this is not an issue with this repo. If you can post the full notebook to the support forum, we can follow up there.  
I'll close this issue for now.

**Closed as completed by cathalmccabe** 2018-10-19 09:47 UTC
